services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: amalthea-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: amalthea
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - amalthea-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amalthea-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/amalthea?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - amalthea-network
    volumes:
      - ./uploads:/app/uploads

  # MongoDB Express (Database Admin UI) - Optional
  mongo-express:
    image: mongo-express:1.0.2
    container_name: amalthea-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - amalthea-network

volumes:
  mongodb_data:
    driver: local

networks:
  amalthea-network:
    driver: bridge
